NodeStatementsIterator and some minor 'storing' pkg improvements.
alexeykiselev/nodemon pull request #6
Opened 2022-02-10 17:36 UTC by nickeskov

2022-02-15 08:23 UTC, alexeykiselev requested changes

2022-02-15 08:27 UTC, nickeskov commented on pkg/analysis/alert.go
> +type Alert struct {
Yep, it is. But it's temporary stub. I'll rewrite it in next pr. Though, I'll move it to notifications in this PR.

2022-02-15 15:12 UTC, nickeskov commented on pkg/analysis/alert.go
> +type Alert struct {
Moved.

2022-02-17 10:56 UTC, alexeykiselev approved these changes

2022-02-17 10:56 UTC, merged